theme: minima
title: Piotr Kawa
# description: 123123


author:
  name: Piotr Kawa
  email: piotr.kawa@pwr.edu.pl
description: > # this means to ignore newlines until "show_excerpts:"
show_excerpts: false # set to true to show excerpts on the homepage